name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  relese:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: volta-cli/action@v4
    - run: volta install pnpm
    - run: pnpm install
    - run: pnpm run build

    