name: check

on:
    push:

permissions:
    contents: write

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Volta
              uses: volta-cli/action@v4

            - name: Install dependencies
              run: ./devtools.sh init

            - name: Run ESLint
              run: pnpm run lint
